# Generated by Django 6.0.6 on 2026-06-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_emergencyalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
