# Generated by Django 6.0.6 on 2026-06-05 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.doctor'),
        ),
    ]
